apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-ui-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: pipelines-hello-manoj
  - name: git-url
    value: https://github.com/manojto/hello-manoj.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/openshift/hello-manoj:latest
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
